---
- name: Install helm
  include_tasks: install-helm.yml

- name: Get all repos
  register: helm_registered_repos
  shell: "{{ kubernetes_helm_bin_dir }}/helm repo list | grep -v NAME | awk '{print $1}'"
  changed_when: helm_registered_repos.rc == 0

- name: Add repos
  command: "{{ kubernetes_helm_bin_dir }}/helm repo add {{ item.name }} {{ item.url }}"
  register: result
  changed_when: result.rc == 0
  when: ( item.state is not defined ) or (item.state == 'present')
  loop: '{{ m7s_k8s_helm_repos | default([]) }}'

- name: Remove repos
  command: "{{ kubernetes_helm_bin_dir }}/helm repo remove {{ item.name }}"
  register: result
  changed_when: result.rc == 0
  when: ( item.state is defined ) and ( item.state == 'absent' ) and
        ( item.name in helm_registered_repos.stdout_lines )
  loop: '{{ m7s_k8s_helm_repos | default([]) }}'

- name: Update repos
  command: "{{ kubernetes_helm_bin_dir }}/helm repo update"
  register: result
  changed_when: result.rc == 0

- name: Install charts
  include_tasks: install-chart.yml
  when: ( chart.state is not defined ) or ( chart.state == 'present')
  loop: '{{ m7s_k8s_helm_charts | default([]) }}'
  loop_control:
    loop_var: chart

- name: Remove charts
  include_tasks: remove-chart.yml
  when: ( chart.state is defined ) and ( chart.state == 'absent')
  loop: '{{ m7s_k8s_helm_charts | default([]) }}'
  loop_control:
    loop_var: chart
