
- name: Set helm cmd namespace
  set_fact:
    helm_chart_namespace: " -n {{ chart.namespace }}"
  when: chart.namespace is defined

- name: Check if installed
  shell: helm status{{ helm_chart_namespace }} {{ chart.name }}
  register: helm_status_cmd
  ignore_errors: True

- name: Set vars
  set_fact:
    chart_installed: "{{ helm_status_cmd.rc == 0 }}"


- name: Install chart
  shell: helm uninstall {{ chart.name }}{{ helm_chart_namespace | default('') }}
  when: chart_installed
