
- name: Set helm cmd namespace
  set_fact:
    helm_chart_namespace: " -n {{ chart.namespace }}"
  when: chart.namespace is defined

- name: Check if installed
  command: helm status{{ helm_chart_namespace }} {{ chart.name }}
  register: helm_status_cmd
  ignore_errors: True
  changed_when: False

- name: Set vars
  set_fact:
    chart_installed: "{{ helm_status_cmd.rc == 0 }}"


- name: Uninstall chart
  command: helm uninstall {{ chart.name }}{{ helm_chart_namespace | default('') }}
  register: result
  changed_when: result.rc == 0
  when: chart_installed
